apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wpdb
  name: wpdb
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_DATABASE
      value: wpdb
    - name: MYSQL_USER
      value: umesh
    - name: MYSQL_PASSWORD
      value: redhat
    image: mysql:5.7
    name: wpdb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
