apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wp
  name: wp
spec:
  containers:
  - image: wordpress:5.1.1-php7.3-apache
    name: wp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: wp
  name: wp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wp
  type: NodePort
status:
  loadBalancer: {}
